apiVersion: v1
kind: Pod
metadata:
  name: hello-deployment
spec:
  containers:
  - name: hello-container
    image: deena08/helloapp:v1.0
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-auto
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: pod
    name: hello-deployment
  minReplicas: 1 
  maxReplicas: 5 
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30    
    