apiVersion: v1
kind: Service
metadata:
  name: helloapp-service
spec:
  type: NodePort
  selector:
    app: hello
  ports:
  - name: hello-deployment-5dd8665d5f-c7chz 
    port: 30001  
    targetPort: 8000 
    nodePort: 30001  
  - name: hello-deployment-5dd8665d5f-g9lsx 
    port: 30002 
    targetPort: 8000  
    nodePort: 30002  
  - name: hello-deployment-5dd8665d5f-qkkdd
    port: 30003  
    targetPort: 8000 
    nodePort: 30003  